version: "2.2.3"

services:

  nginx:
    build: ./nginx
    container_name: nginx
    image: nginx
    depends_on:
      - wordpress
    env_file:
      - ./.env
    ports:
      - 443:443
    volumes:
      - /home/gcefalo/data/wordpress:/var/www/gcefalo
    networks:
      - inception_network
    restart: unless-stopped

  wordpress:
    build: ./wordpress
    container_name: wordpress
    image: wordpress
    depends_on:
      - mariadb
    env_file:
      - ./.env
    volumes:
      - /home/gcefalo/data/wordpress:/var/www/gcefalo
    networks:
      - inception_network
    restart: unless-stopped

  mariadb:
    build: ./mariadb
    container_name: mariadb
    image: mariadb
    env_file:
      - ./.env
    volumes:
      - /home/gcefalo/data/db:/var/lib/mysql
    networks:
      - inception_network
    restart: unless-stopped

networks:
  inception_network:
    driver: bridge
